
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action SaveAction;

	private global::Gtk.Action SaveAsAction;

	private global::Gtk.Action OpenAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Button start_stop;

	private global::Gtk.Table table1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.HSeparator hseparator10;

	private global::Gtk.HSeparator hseparator11;

	private global::Gtk.HSeparator hseparator12;

	private global::Gtk.HSeparator hseparator13;

	private global::Gtk.HSeparator hseparator14;

	private global::Gtk.HSeparator hseparator15;

	private global::Gtk.HSeparator hseparator16;

	private global::Gtk.HSeparator hseparator17;

	private global::Gtk.HSeparator hseparator18;

	private global::Gtk.HSeparator hseparator19;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.HSeparator hseparator20;

	private global::Gtk.HSeparator hseparator21;

	private global::Gtk.HSeparator hseparator22;

	private global::Gtk.HSeparator hseparator23;

	private global::Gtk.HSeparator hseparator24;

	private global::Gtk.HSeparator hseparator25;

	private global::Gtk.HSeparator hseparator26;

	private global::Gtk.HSeparator hseparator27;

	private global::Gtk.HSeparator hseparator28;

	private global::Gtk.HSeparator hseparator29;

	private global::Gtk.HSeparator hseparator3;

	private global::Gtk.HSeparator hseparator30;

	private global::Gtk.HSeparator hseparator31;

	private global::Gtk.HSeparator hseparator32;

	private global::Gtk.HSeparator hseparator33;

	private global::Gtk.HSeparator hseparator34;

	private global::Gtk.HSeparator hseparator35;

	private global::Gtk.HSeparator hseparator4;

	private global::Gtk.HSeparator hseparator5;

	private global::Gtk.HSeparator hseparator6;

	private global::Gtk.HSeparator hseparator7;

	private global::Gtk.HSeparator hseparator8;

	private global::Gtk.HSeparator hseparator9;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.ProgressBar progressbar1;

	private global::Gtk.ProgressBar progressbar2;

	private global::Gtk.ProgressBar progressbar3;

	private global::Gtk.ProgressBar progressbar4;

	private global::Gtk.ProgressBar progressbar5;

	private global::Gtk.Table table3;

	private global::Gtk.CheckButton checkbutton1;

	private global::Gtk.Entry entry1;

	private global::Gtk.Entry entry2;

	private global::Gtk.Entry entry3;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.Table table4;

	private global::Gtk.CheckButton checkbutton2;

	private global::Gtk.Entry entry5;

	private global::Gtk.Entry entry6;

	private global::Gtk.Entry entry7;

	private global::Gtk.Label label10;

	private global::Gtk.Label label11;

	private global::Gtk.Label label12;

	private global::Gtk.Label label13;

	private global::Gtk.Table table5;

	private global::Gtk.CheckButton checkbutton3;

	private global::Gtk.Entry entry10;

	private global::Gtk.Entry entry11;

	private global::Gtk.Entry entry9;

	private global::Gtk.Label label14;

	private global::Gtk.Label label15;

	private global::Gtk.Label label16;

	private global::Gtk.Label label17;

	private global::Gtk.Table table6;

	private global::Gtk.CheckButton checkbutton4;

	private global::Gtk.Entry entry13;

	private global::Gtk.Entry entry14;

	private global::Gtk.Entry entry15;

	private global::Gtk.Label label18;

	private global::Gtk.Label label19;

	private global::Gtk.Label label20;

	private global::Gtk.Label label21;

	private global::Gtk.Table table7;

	private global::Gtk.CheckButton checkbutton5;

	private global::Gtk.Entry entry16;

	private global::Gtk.Entry entry17;

	private global::Gtk.Entry entry18;

	private global::Gtk.Label label22;

	private global::Gtk.Label label23;

	private global::Gtk.Label label24;

	private global::Gtk.Label label25;

	private global::Gtk.VBox vbox3;

	private global::Gtk.RadioButton common1;

	private global::Gtk.RadioButton railway1;

	private global::Gtk.RadioButton electrified1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.RadioButton common2;

	private global::Gtk.RadioButton railway2;

	private global::Gtk.RadioButton electrified2;

	private global::Gtk.VBox vbox5;

	private global::Gtk.RadioButton common3;

	private global::Gtk.RadioButton railway3;

	private global::Gtk.RadioButton electrified3;

	private global::Gtk.VBox vbox6;

	private global::Gtk.RadioButton common4;

	private global::Gtk.RadioButton railway4;

	private global::Gtk.RadioButton electrified4;

	private global::Gtk.VBox vbox7;

	private global::Gtk.RadioButton common5;

	private global::Gtk.RadioButton railway5;

	private global::Gtk.RadioButton electrified5;

	private global::Gtk.Table table2;

	private global::Gtk.Label elTime;

	private global::Gtk.Label numTransport;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.Statusbar statusbar2;

	private global::Gtk.Statusbar statusbar3;

	private global::Gtk.Statusbar statusbar4;

	private global::Gtk.Label sumMoveTime;

	private global::Gtk.Label sumStopTime;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.SaveAction = new global::Gtk.Action("SaveAction", global::Mono.Unix.Catalog.GetString("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save");
		w1.Add(this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action("SaveAsAction", global::Mono.Unix.Catalog.GetString("Save as..."), null, null);
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save as...");
		w1.Add(this.SaveAsAction, null);
		this.OpenAction = new global::Gtk.Action("OpenAction", global::Mono.Unix.Catalog.GetString("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open");
		w1.Add(this.OpenAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar1\'><menu name=\'FileAction\' action=\'FileAction\'><menuite" +
				"m name=\'SaveAction\' action=\'SaveAction\'/><menuitem name=\'SaveAsAction\' action=\'S" +
				"aveAsAction\'/><menuitem name=\'OpenAction\' action=\'OpenAction\'/></menu></menubar>" +
				"</ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.start_stop = new global::Gtk.Button();
		this.start_stop.CanFocus = true;
		this.start_stop.Name = "start_stop";
		this.start_stop.UseUnderline = true;
		this.start_stop.Label = global::Mono.Unix.Catalog.GetString("START/STOP");
		this.vbox1.Add(this.start_stop);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.start_stop]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(12)), ((uint)(5)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
		this.table1.Add(this.button1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.button1]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(4));
		w4.RightAttach = ((uint)(5));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
		this.table1.Add(this.button2);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.button2]));
		w5.TopAttach = ((uint)(3));
		w5.BottomAttach = ((uint)(4));
		w5.LeftAttach = ((uint)(4));
		w5.RightAttach = ((uint)(5));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
		this.table1.Add(this.button3);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.button3]));
		w6.TopAttach = ((uint)(5));
		w6.BottomAttach = ((uint)(6));
		w6.LeftAttach = ((uint)(4));
		w6.RightAttach = ((uint)(5));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
		this.table1.Add(this.button4);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.button4]));
		w7.TopAttach = ((uint)(7));
		w7.BottomAttach = ((uint)(8));
		w7.LeftAttach = ((uint)(4));
		w7.RightAttach = ((uint)(5));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Add Transport");
		this.table1.Add(this.button5);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.button5]));
		w8.TopAttach = ((uint)(9));
		w8.BottomAttach = ((uint)(10));
		w8.LeftAttach = ((uint)(4));
		w8.RightAttach = ((uint)(5));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.table1.Add(this.hseparator1);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator1]));
		w9.LeftAttach = ((uint)(4));
		w9.RightAttach = ((uint)(5));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator10 = new global::Gtk.HSeparator();
		this.hseparator10.Name = "hseparator10";
		this.table1.Add(this.hseparator10);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator10]));
		w10.TopAttach = ((uint)(4));
		w10.BottomAttach = ((uint)(5));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator11 = new global::Gtk.HSeparator();
		this.hseparator11.Name = "hseparator11";
		this.table1.Add(this.hseparator11);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator11]));
		w11.TopAttach = ((uint)(4));
		w11.BottomAttach = ((uint)(5));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator12 = new global::Gtk.HSeparator();
		this.hseparator12.Name = "hseparator12";
		this.table1.Add(this.hseparator12);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator12]));
		w12.TopAttach = ((uint)(4));
		w12.BottomAttach = ((uint)(5));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator13 = new global::Gtk.HSeparator();
		this.hseparator13.Name = "hseparator13";
		this.table1.Add(this.hseparator13);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator13]));
		w13.TopAttach = ((uint)(6));
		w13.BottomAttach = ((uint)(7));
		w13.LeftAttach = ((uint)(4));
		w13.RightAttach = ((uint)(5));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator14 = new global::Gtk.HSeparator();
		this.hseparator14.Name = "hseparator14";
		this.table1.Add(this.hseparator14);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator14]));
		w14.TopAttach = ((uint)(6));
		w14.BottomAttach = ((uint)(7));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator15 = new global::Gtk.HSeparator();
		this.hseparator15.Name = "hseparator15";
		this.table1.Add(this.hseparator15);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator15]));
		w15.TopAttach = ((uint)(6));
		w15.BottomAttach = ((uint)(7));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator16 = new global::Gtk.HSeparator();
		this.hseparator16.Name = "hseparator16";
		this.table1.Add(this.hseparator16);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator16]));
		w16.TopAttach = ((uint)(6));
		w16.BottomAttach = ((uint)(7));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator17 = new global::Gtk.HSeparator();
		this.hseparator17.Name = "hseparator17";
		this.table1.Add(this.hseparator17);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator17]));
		w17.TopAttach = ((uint)(11));
		w17.BottomAttach = ((uint)(12));
		w17.LeftAttach = ((uint)(4));
		w17.RightAttach = ((uint)(5));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator18 = new global::Gtk.HSeparator();
		this.hseparator18.Name = "hseparator18";
		this.table1.Add(this.hseparator18);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator18]));
		w18.TopAttach = ((uint)(11));
		w18.BottomAttach = ((uint)(12));
		w18.LeftAttach = ((uint)(2));
		w18.RightAttach = ((uint)(3));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator19 = new global::Gtk.HSeparator();
		this.hseparator19.Name = "hseparator19";
		this.table1.Add(this.hseparator19);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator19]));
		w19.TopAttach = ((uint)(11));
		w19.BottomAttach = ((uint)(12));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.table1.Add(this.hseparator2);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator2]));
		w20.LeftAttach = ((uint)(2));
		w20.RightAttach = ((uint)(3));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator20 = new global::Gtk.HSeparator();
		this.hseparator20.Name = "hseparator20";
		this.table1.Add(this.hseparator20);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator20]));
		w21.TopAttach = ((uint)(11));
		w21.BottomAttach = ((uint)(12));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator21 = new global::Gtk.HSeparator();
		this.hseparator21.Name = "hseparator21";
		this.table1.Add(this.hseparator21);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator21]));
		w22.LeftAttach = ((uint)(3));
		w22.RightAttach = ((uint)(4));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator22 = new global::Gtk.HSeparator();
		this.hseparator22.Name = "hseparator22";
		this.table1.Add(this.hseparator22);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator22]));
		w23.TopAttach = ((uint)(10));
		w23.BottomAttach = ((uint)(11));
		w23.LeftAttach = ((uint)(4));
		w23.RightAttach = ((uint)(5));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator23 = new global::Gtk.HSeparator();
		this.hseparator23.Name = "hseparator23";
		this.table1.Add(this.hseparator23);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator23]));
		w24.TopAttach = ((uint)(10));
		w24.BottomAttach = ((uint)(11));
		w24.LeftAttach = ((uint)(2));
		w24.RightAttach = ((uint)(3));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator24 = new global::Gtk.HSeparator();
		this.hseparator24.Name = "hseparator24";
		this.table1.Add(this.hseparator24);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator24]));
		w25.TopAttach = ((uint)(10));
		w25.BottomAttach = ((uint)(11));
		w25.LeftAttach = ((uint)(1));
		w25.RightAttach = ((uint)(2));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator25 = new global::Gtk.HSeparator();
		this.hseparator25.Name = "hseparator25";
		this.table1.Add(this.hseparator25);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator25]));
		w26.TopAttach = ((uint)(10));
		w26.BottomAttach = ((uint)(11));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator26 = new global::Gtk.HSeparator();
		this.hseparator26.Name = "hseparator26";
		this.table1.Add(this.hseparator26);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator26]));
		w27.TopAttach = ((uint)(8));
		w27.BottomAttach = ((uint)(9));
		w27.LeftAttach = ((uint)(4));
		w27.RightAttach = ((uint)(5));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator27 = new global::Gtk.HSeparator();
		this.hseparator27.Name = "hseparator27";
		this.table1.Add(this.hseparator27);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator27]));
		w28.TopAttach = ((uint)(8));
		w28.BottomAttach = ((uint)(9));
		w28.LeftAttach = ((uint)(2));
		w28.RightAttach = ((uint)(3));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator28 = new global::Gtk.HSeparator();
		this.hseparator28.Name = "hseparator28";
		this.table1.Add(this.hseparator28);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator28]));
		w29.TopAttach = ((uint)(8));
		w29.BottomAttach = ((uint)(9));
		w29.LeftAttach = ((uint)(1));
		w29.RightAttach = ((uint)(2));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator29 = new global::Gtk.HSeparator();
		this.hseparator29.Name = "hseparator29";
		this.table1.Add(this.hseparator29);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator29]));
		w30.TopAttach = ((uint)(8));
		w30.BottomAttach = ((uint)(9));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.Name = "hseparator3";
		this.table1.Add(this.hseparator3);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator3]));
		w31.LeftAttach = ((uint)(1));
		w31.RightAttach = ((uint)(2));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator30 = new global::Gtk.HSeparator();
		this.hseparator30.Name = "hseparator30";
		this.table1.Add(this.hseparator30);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator30]));
		w32.TopAttach = ((uint)(2));
		w32.BottomAttach = ((uint)(3));
		w32.LeftAttach = ((uint)(3));
		w32.RightAttach = ((uint)(4));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator31 = new global::Gtk.HSeparator();
		this.hseparator31.Name = "hseparator31";
		this.table1.Add(this.hseparator31);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator31]));
		w33.TopAttach = ((uint)(6));
		w33.BottomAttach = ((uint)(7));
		w33.LeftAttach = ((uint)(3));
		w33.RightAttach = ((uint)(4));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator32 = new global::Gtk.HSeparator();
		this.hseparator32.Name = "hseparator32";
		this.table1.Add(this.hseparator32);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator32]));
		w34.TopAttach = ((uint)(4));
		w34.BottomAttach = ((uint)(5));
		w34.LeftAttach = ((uint)(3));
		w34.RightAttach = ((uint)(4));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator33 = new global::Gtk.HSeparator();
		this.hseparator33.Name = "hseparator33";
		this.table1.Add(this.hseparator33);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator33]));
		w35.TopAttach = ((uint)(8));
		w35.BottomAttach = ((uint)(9));
		w35.LeftAttach = ((uint)(3));
		w35.RightAttach = ((uint)(4));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator34 = new global::Gtk.HSeparator();
		this.hseparator34.Name = "hseparator34";
		this.table1.Add(this.hseparator34);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator34]));
		w36.TopAttach = ((uint)(10));
		w36.BottomAttach = ((uint)(11));
		w36.LeftAttach = ((uint)(3));
		w36.RightAttach = ((uint)(4));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator35 = new global::Gtk.HSeparator();
		this.hseparator35.Name = "hseparator35";
		this.table1.Add(this.hseparator35);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator35]));
		w37.TopAttach = ((uint)(11));
		w37.BottomAttach = ((uint)(12));
		w37.LeftAttach = ((uint)(3));
		w37.RightAttach = ((uint)(4));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator4 = new global::Gtk.HSeparator();
		this.hseparator4.Name = "hseparator4";
		this.table1.Add(this.hseparator4);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator4]));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator5 = new global::Gtk.HSeparator();
		this.hseparator5.Name = "hseparator5";
		this.table1.Add(this.hseparator5);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator5]));
		w39.TopAttach = ((uint)(2));
		w39.BottomAttach = ((uint)(3));
		w39.LeftAttach = ((uint)(4));
		w39.RightAttach = ((uint)(5));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator6 = new global::Gtk.HSeparator();
		this.hseparator6.Name = "hseparator6";
		this.table1.Add(this.hseparator6);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator6]));
		w40.TopAttach = ((uint)(2));
		w40.BottomAttach = ((uint)(3));
		w40.LeftAttach = ((uint)(2));
		w40.RightAttach = ((uint)(3));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator7 = new global::Gtk.HSeparator();
		this.hseparator7.Name = "hseparator7";
		this.table1.Add(this.hseparator7);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator7]));
		w41.TopAttach = ((uint)(2));
		w41.BottomAttach = ((uint)(3));
		w41.LeftAttach = ((uint)(1));
		w41.RightAttach = ((uint)(2));
		w41.XOptions = ((global::Gtk.AttachOptions)(4));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator8 = new global::Gtk.HSeparator();
		this.hseparator8.Name = "hseparator8";
		this.table1.Add(this.hseparator8);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator8]));
		w42.TopAttach = ((uint)(2));
		w42.BottomAttach = ((uint)(3));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator9 = new global::Gtk.HSeparator();
		this.hseparator9.Name = "hseparator9";
		this.table1.Add(this.hseparator9);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator9]));
		w43.TopAttach = ((uint)(4));
		w43.BottomAttach = ((uint)(5));
		w43.LeftAttach = ((uint)(4));
		w43.RightAttach = ((uint)(5));
		w43.XOptions = ((global::Gtk.AttachOptions)(4));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("№ 1");
		this.table1.Add(this.label1);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
		w44.TopAttach = ((uint)(1));
		w44.BottomAttach = ((uint)(2));
		w44.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("№ 2");
		this.table1.Add(this.label2);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
		w45.TopAttach = ((uint)(3));
		w45.BottomAttach = ((uint)(4));
		w45.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("№ 3");
		this.table1.Add(this.label3);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
		w46.TopAttach = ((uint)(5));
		w46.BottomAttach = ((uint)(6));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("№ 4");
		this.table1.Add(this.label4);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
		w47.TopAttach = ((uint)(7));
		w47.BottomAttach = ((uint)(8));
		w47.XOptions = ((global::Gtk.AttachOptions)(4));
		w47.YOptions = ((global::Gtk.AttachOptions)(1));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("№ 5");
		this.table1.Add(this.label5);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
		w48.TopAttach = ((uint)(9));
		w48.BottomAttach = ((uint)(10));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.progressbar1 = new global::Gtk.ProgressBar();
		this.progressbar1.Name = "progressbar1";
		this.table1.Add(this.progressbar1);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1[this.progressbar1]));
		w49.TopAttach = ((uint)(1));
		w49.BottomAttach = ((uint)(2));
		w49.LeftAttach = ((uint)(2));
		w49.RightAttach = ((uint)(3));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.progressbar2 = new global::Gtk.ProgressBar();
		this.progressbar2.Name = "progressbar2";
		this.table1.Add(this.progressbar2);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table1[this.progressbar2]));
		w50.TopAttach = ((uint)(3));
		w50.BottomAttach = ((uint)(4));
		w50.LeftAttach = ((uint)(2));
		w50.RightAttach = ((uint)(3));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.progressbar3 = new global::Gtk.ProgressBar();
		this.progressbar3.Name = "progressbar3";
		this.table1.Add(this.progressbar3);
		global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table1[this.progressbar3]));
		w51.TopAttach = ((uint)(5));
		w51.BottomAttach = ((uint)(6));
		w51.LeftAttach = ((uint)(2));
		w51.RightAttach = ((uint)(3));
		w51.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.progressbar4 = new global::Gtk.ProgressBar();
		this.progressbar4.Name = "progressbar4";
		this.table1.Add(this.progressbar4);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table1[this.progressbar4]));
		w52.TopAttach = ((uint)(7));
		w52.BottomAttach = ((uint)(8));
		w52.LeftAttach = ((uint)(2));
		w52.RightAttach = ((uint)(3));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.progressbar5 = new global::Gtk.ProgressBar();
		this.progressbar5.Name = "progressbar5";
		this.table1.Add(this.progressbar5);
		global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table1[this.progressbar5]));
		w53.TopAttach = ((uint)(9));
		w53.BottomAttach = ((uint)(10));
		w53.LeftAttach = ((uint)(2));
		w53.RightAttach = ((uint)(3));
		w53.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table3 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.checkbutton1 = new global::Gtk.CheckButton();
		this.checkbutton1.Sensitive = false;
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = "";
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.table3.Add(this.checkbutton1);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table3[this.checkbutton1]));
		w54.TopAttach = ((uint)(3));
		w54.BottomAttach = ((uint)(4));
		w54.LeftAttach = ((uint)(1));
		w54.RightAttach = ((uint)(2));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.Sensitive = false;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.Text = global::Mono.Unix.Catalog.GetString("param 1 value");
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.table3.Add(this.entry1);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table3[this.entry1]));
		w55.LeftAttach = ((uint)(1));
		w55.RightAttach = ((uint)(2));
		w55.XOptions = ((global::Gtk.AttachOptions)(0));
		w55.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table3.Gtk.Table+TableChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.Sensitive = false;
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.Text = global::Mono.Unix.Catalog.GetString("param 2 value");
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.table3.Add(this.entry2);
		global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table3[this.entry2]));
		w56.TopAttach = ((uint)(1));
		w56.BottomAttach = ((uint)(2));
		w56.LeftAttach = ((uint)(1));
		w56.RightAttach = ((uint)(2));
		w56.XOptions = ((global::Gtk.AttachOptions)(4));
		w56.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.Sensitive = false;
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.Text = global::Mono.Unix.Catalog.GetString("param 3 value");
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.table3.Add(this.entry3);
		global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table3[this.entry3]));
		w57.TopAttach = ((uint)(2));
		w57.BottomAttach = ((uint)(3));
		w57.LeftAttach = ((uint)(1));
		w57.RightAttach = ((uint)(2));
		w57.XOptions = ((global::Gtk.AttachOptions)(4));
		w57.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Param1");
		this.table3.Add(this.label6);
		global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table3[this.label6]));
		w58.XOptions = ((global::Gtk.AttachOptions)(4));
		w58.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Param2");
		this.table3.Add(this.label7);
		global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
		w59.TopAttach = ((uint)(1));
		w59.BottomAttach = ((uint)(2));
		w59.XOptions = ((global::Gtk.AttachOptions)(4));
		w59.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Param3");
		this.table3.Add(this.label8);
		global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table3[this.label8]));
		w60.TopAttach = ((uint)(2));
		w60.BottomAttach = ((uint)(3));
		w60.XOptions = ((global::Gtk.AttachOptions)(4));
		w60.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Param4");
		this.table3.Add(this.label9);
		global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table3[this.label9]));
		w61.TopAttach = ((uint)(3));
		w61.BottomAttach = ((uint)(4));
		w61.XOptions = ((global::Gtk.AttachOptions)(4));
		w61.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add(this.table3);
		global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table1[this.table3]));
		w62.TopAttach = ((uint)(1));
		w62.BottomAttach = ((uint)(2));
		w62.LeftAttach = ((uint)(3));
		w62.RightAttach = ((uint)(4));
		w62.XOptions = ((global::Gtk.AttachOptions)(0));
		w62.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table4 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.checkbutton2 = new global::Gtk.CheckButton();
		this.checkbutton2.Sensitive = false;
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = "";
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.table4.Add(this.checkbutton2);
		global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table4[this.checkbutton2]));
		w63.TopAttach = ((uint)(3));
		w63.BottomAttach = ((uint)(4));
		w63.LeftAttach = ((uint)(1));
		w63.RightAttach = ((uint)(2));
		w63.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.Sensitive = false;
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.Text = global::Mono.Unix.Catalog.GetString("param 1 value");
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.table4.Add(this.entry5);
		global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table4[this.entry5]));
		w64.LeftAttach = ((uint)(1));
		w64.RightAttach = ((uint)(2));
		w64.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.entry6 = new global::Gtk.Entry();
		this.entry6.Sensitive = false;
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.Text = global::Mono.Unix.Catalog.GetString("param 2 value");
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.table4.Add(this.entry6);
		global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table4[this.entry6]));
		w65.TopAttach = ((uint)(1));
		w65.BottomAttach = ((uint)(2));
		w65.LeftAttach = ((uint)(1));
		w65.RightAttach = ((uint)(2));
		w65.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.entry7 = new global::Gtk.Entry();
		this.entry7.Sensitive = false;
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.Text = global::Mono.Unix.Catalog.GetString("param 3 value");
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '●';
		this.table4.Add(this.entry7);
		global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table4[this.entry7]));
		w66.TopAttach = ((uint)(2));
		w66.BottomAttach = ((uint)(3));
		w66.LeftAttach = ((uint)(1));
		w66.RightAttach = ((uint)(2));
		w66.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Param1");
		this.table4.Add(this.label10);
		global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table4[this.label10]));
		w67.XOptions = ((global::Gtk.AttachOptions)(4));
		w67.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Param2");
		this.table4.Add(this.label11);
		global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table4[this.label11]));
		w68.TopAttach = ((uint)(1));
		w68.BottomAttach = ((uint)(2));
		w68.XOptions = ((global::Gtk.AttachOptions)(4));
		w68.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Param3");
		this.table4.Add(this.label12);
		global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table4[this.label12]));
		w69.TopAttach = ((uint)(2));
		w69.BottomAttach = ((uint)(3));
		w69.XOptions = ((global::Gtk.AttachOptions)(4));
		w69.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Param4");
		this.table4.Add(this.label13);
		global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table4[this.label13]));
		w70.TopAttach = ((uint)(3));
		w70.BottomAttach = ((uint)(4));
		w70.XOptions = ((global::Gtk.AttachOptions)(4));
		w70.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add(this.table4);
		global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table1[this.table4]));
		w71.TopAttach = ((uint)(3));
		w71.BottomAttach = ((uint)(4));
		w71.LeftAttach = ((uint)(3));
		w71.RightAttach = ((uint)(4));
		w71.XOptions = ((global::Gtk.AttachOptions)(4));
		w71.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table5 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(6));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.checkbutton3 = new global::Gtk.CheckButton();
		this.checkbutton3.Sensitive = false;
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = "";
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.table5.Add(this.checkbutton3);
		global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table5[this.checkbutton3]));
		w72.TopAttach = ((uint)(3));
		w72.BottomAttach = ((uint)(4));
		w72.LeftAttach = ((uint)(1));
		w72.RightAttach = ((uint)(2));
		w72.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.entry10 = new global::Gtk.Entry();
		this.entry10.Sensitive = false;
		this.entry10.CanFocus = true;
		this.entry10.Name = "entry10";
		this.entry10.Text = global::Mono.Unix.Catalog.GetString("param 2 value");
		this.entry10.IsEditable = true;
		this.entry10.InvisibleChar = '●';
		this.table5.Add(this.entry10);
		global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.table5[this.entry10]));
		w73.TopAttach = ((uint)(1));
		w73.BottomAttach = ((uint)(2));
		w73.LeftAttach = ((uint)(1));
		w73.RightAttach = ((uint)(2));
		w73.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.entry11 = new global::Gtk.Entry();
		this.entry11.Sensitive = false;
		this.entry11.CanFocus = true;
		this.entry11.Name = "entry11";
		this.entry11.Text = global::Mono.Unix.Catalog.GetString("param 3 value");
		this.entry11.IsEditable = true;
		this.entry11.InvisibleChar = '●';
		this.table5.Add(this.entry11);
		global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table5[this.entry11]));
		w74.TopAttach = ((uint)(2));
		w74.BottomAttach = ((uint)(3));
		w74.LeftAttach = ((uint)(1));
		w74.RightAttach = ((uint)(2));
		w74.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.entry9 = new global::Gtk.Entry();
		this.entry9.Sensitive = false;
		this.entry9.CanFocus = true;
		this.entry9.Name = "entry9";
		this.entry9.Text = global::Mono.Unix.Catalog.GetString("param 1 value");
		this.entry9.IsEditable = true;
		this.entry9.InvisibleChar = '●';
		this.table5.Add(this.entry9);
		global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table5[this.entry9]));
		w75.LeftAttach = ((uint)(1));
		w75.RightAttach = ((uint)(2));
		w75.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Param1");
		this.table5.Add(this.label14);
		global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table5[this.label14]));
		w76.XOptions = ((global::Gtk.AttachOptions)(4));
		w76.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Param2");
		this.table5.Add(this.label15);
		global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table5[this.label15]));
		w77.TopAttach = ((uint)(1));
		w77.BottomAttach = ((uint)(2));
		w77.XOptions = ((global::Gtk.AttachOptions)(4));
		w77.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Param3");
		this.table5.Add(this.label16);
		global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table5[this.label16]));
		w78.TopAttach = ((uint)(2));
		w78.BottomAttach = ((uint)(3));
		w78.XOptions = ((global::Gtk.AttachOptions)(4));
		w78.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Param4");
		this.table5.Add(this.label17);
		global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table5[this.label17]));
		w79.TopAttach = ((uint)(3));
		w79.BottomAttach = ((uint)(4));
		w79.XOptions = ((global::Gtk.AttachOptions)(4));
		w79.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add(this.table5);
		global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table1[this.table5]));
		w80.TopAttach = ((uint)(5));
		w80.BottomAttach = ((uint)(6));
		w80.LeftAttach = ((uint)(3));
		w80.RightAttach = ((uint)(4));
		w80.XOptions = ((global::Gtk.AttachOptions)(4));
		w80.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table6 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
		this.table6.Name = "table6";
		this.table6.RowSpacing = ((uint)(6));
		this.table6.ColumnSpacing = ((uint)(6));
		// Container child table6.Gtk.Table+TableChild
		this.checkbutton4 = new global::Gtk.CheckButton();
		this.checkbutton4.Sensitive = false;
		this.checkbutton4.CanFocus = true;
		this.checkbutton4.Name = "checkbutton4";
		this.checkbutton4.Label = "";
		this.checkbutton4.DrawIndicator = true;
		this.checkbutton4.UseUnderline = true;
		this.table6.Add(this.checkbutton4);
		global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table6[this.checkbutton4]));
		w81.TopAttach = ((uint)(3));
		w81.BottomAttach = ((uint)(4));
		w81.LeftAttach = ((uint)(1));
		w81.RightAttach = ((uint)(2));
		w81.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.entry13 = new global::Gtk.Entry();
		this.entry13.Sensitive = false;
		this.entry13.CanFocus = true;
		this.entry13.Name = "entry13";
		this.entry13.Text = global::Mono.Unix.Catalog.GetString("param 1 value");
		this.entry13.IsEditable = true;
		this.entry13.InvisibleChar = '●';
		this.table6.Add(this.entry13);
		global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table6[this.entry13]));
		w82.LeftAttach = ((uint)(1));
		w82.RightAttach = ((uint)(2));
		w82.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.entry14 = new global::Gtk.Entry();
		this.entry14.Sensitive = false;
		this.entry14.CanFocus = true;
		this.entry14.Name = "entry14";
		this.entry14.Text = global::Mono.Unix.Catalog.GetString("param 2 value");
		this.entry14.IsEditable = true;
		this.entry14.InvisibleChar = '●';
		this.table6.Add(this.entry14);
		global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table6[this.entry14]));
		w83.TopAttach = ((uint)(1));
		w83.BottomAttach = ((uint)(2));
		w83.LeftAttach = ((uint)(1));
		w83.RightAttach = ((uint)(2));
		w83.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.entry15 = new global::Gtk.Entry();
		this.entry15.Sensitive = false;
		this.entry15.CanFocus = true;
		this.entry15.Name = "entry15";
		this.entry15.Text = global::Mono.Unix.Catalog.GetString("param 3 value");
		this.entry15.IsEditable = true;
		this.entry15.InvisibleChar = '●';
		this.table6.Add(this.entry15);
		global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table6[this.entry15]));
		w84.TopAttach = ((uint)(2));
		w84.BottomAttach = ((uint)(3));
		w84.LeftAttach = ((uint)(1));
		w84.RightAttach = ((uint)(2));
		w84.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Param1");
		this.table6.Add(this.label18);
		global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table6[this.label18]));
		w85.XOptions = ((global::Gtk.AttachOptions)(4));
		w85.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Param2");
		this.table6.Add(this.label19);
		global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table6[this.label19]));
		w86.TopAttach = ((uint)(1));
		w86.BottomAttach = ((uint)(2));
		w86.XOptions = ((global::Gtk.AttachOptions)(4));
		w86.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Param3");
		this.table6.Add(this.label20);
		global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table6[this.label20]));
		w87.TopAttach = ((uint)(2));
		w87.BottomAttach = ((uint)(3));
		w87.XOptions = ((global::Gtk.AttachOptions)(4));
		w87.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Param4");
		this.table6.Add(this.label21);
		global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.table6[this.label21]));
		w88.TopAttach = ((uint)(3));
		w88.BottomAttach = ((uint)(4));
		w88.XOptions = ((global::Gtk.AttachOptions)(4));
		w88.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add(this.table6);
		global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.table1[this.table6]));
		w89.TopAttach = ((uint)(7));
		w89.BottomAttach = ((uint)(8));
		w89.LeftAttach = ((uint)(3));
		w89.RightAttach = ((uint)(4));
		w89.XOptions = ((global::Gtk.AttachOptions)(4));
		w89.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table7 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
		this.table7.Name = "table7";
		this.table7.RowSpacing = ((uint)(6));
		this.table7.ColumnSpacing = ((uint)(6));
		// Container child table7.Gtk.Table+TableChild
		this.checkbutton5 = new global::Gtk.CheckButton();
		this.checkbutton5.Sensitive = false;
		this.checkbutton5.CanFocus = true;
		this.checkbutton5.Name = "checkbutton5";
		this.checkbutton5.Label = "";
		this.checkbutton5.DrawIndicator = true;
		this.checkbutton5.UseUnderline = true;
		this.table7.Add(this.checkbutton5);
		global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.table7[this.checkbutton5]));
		w90.TopAttach = ((uint)(3));
		w90.BottomAttach = ((uint)(4));
		w90.LeftAttach = ((uint)(1));
		w90.RightAttach = ((uint)(2));
		w90.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.entry16 = new global::Gtk.Entry();
		this.entry16.Sensitive = false;
		this.entry16.CanFocus = true;
		this.entry16.Name = "entry16";
		this.entry16.Text = global::Mono.Unix.Catalog.GetString("param 1 value");
		this.entry16.IsEditable = true;
		this.entry16.InvisibleChar = '●';
		this.table7.Add(this.entry16);
		global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.table7[this.entry16]));
		w91.LeftAttach = ((uint)(1));
		w91.RightAttach = ((uint)(2));
		w91.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.entry17 = new global::Gtk.Entry();
		this.entry17.Sensitive = false;
		this.entry17.CanFocus = true;
		this.entry17.Name = "entry17";
		this.entry17.Text = global::Mono.Unix.Catalog.GetString("param 2 value");
		this.entry17.IsEditable = true;
		this.entry17.InvisibleChar = '●';
		this.table7.Add(this.entry17);
		global::Gtk.Table.TableChild w92 = ((global::Gtk.Table.TableChild)(this.table7[this.entry17]));
		w92.TopAttach = ((uint)(1));
		w92.BottomAttach = ((uint)(2));
		w92.LeftAttach = ((uint)(1));
		w92.RightAttach = ((uint)(2));
		w92.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.entry18 = new global::Gtk.Entry();
		this.entry18.Sensitive = false;
		this.entry18.CanFocus = true;
		this.entry18.Name = "entry18";
		this.entry18.Text = global::Mono.Unix.Catalog.GetString("param 3 value");
		this.entry18.IsEditable = true;
		this.entry18.InvisibleChar = '●';
		this.table7.Add(this.entry18);
		global::Gtk.Table.TableChild w93 = ((global::Gtk.Table.TableChild)(this.table7[this.entry18]));
		w93.TopAttach = ((uint)(2));
		w93.BottomAttach = ((uint)(3));
		w93.LeftAttach = ((uint)(1));
		w93.RightAttach = ((uint)(2));
		w93.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Param1");
		this.table7.Add(this.label22);
		global::Gtk.Table.TableChild w94 = ((global::Gtk.Table.TableChild)(this.table7[this.label22]));
		w94.XOptions = ((global::Gtk.AttachOptions)(4));
		w94.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Param2");
		this.table7.Add(this.label23);
		global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.table7[this.label23]));
		w95.TopAttach = ((uint)(1));
		w95.BottomAttach = ((uint)(2));
		w95.XOptions = ((global::Gtk.AttachOptions)(4));
		w95.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.label24 = new global::Gtk.Label();
		this.label24.Name = "label24";
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Param3");
		this.table7.Add(this.label24);
		global::Gtk.Table.TableChild w96 = ((global::Gtk.Table.TableChild)(this.table7[this.label24]));
		w96.TopAttach = ((uint)(2));
		w96.BottomAttach = ((uint)(3));
		w96.XOptions = ((global::Gtk.AttachOptions)(4));
		w96.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.label25 = new global::Gtk.Label();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Param4");
		this.table7.Add(this.label25);
		global::Gtk.Table.TableChild w97 = ((global::Gtk.Table.TableChild)(this.table7[this.label25]));
		w97.TopAttach = ((uint)(3));
		w97.BottomAttach = ((uint)(4));
		w97.XOptions = ((global::Gtk.AttachOptions)(4));
		w97.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add(this.table7);
		global::Gtk.Table.TableChild w98 = ((global::Gtk.Table.TableChild)(this.table1[this.table7]));
		w98.TopAttach = ((uint)(9));
		w98.BottomAttach = ((uint)(10));
		w98.LeftAttach = ((uint)(3));
		w98.RightAttach = ((uint)(4));
		w98.XOptions = ((global::Gtk.AttachOptions)(4));
		w98.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.common1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
		this.common1.CanFocus = true;
		this.common1.Name = "common1";
		this.common1.DrawIndicator = true;
		this.common1.UseUnderline = true;
		this.common1.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.vbox3.Add(this.common1);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.common1]));
		w99.Position = 0;
		w99.Expand = false;
		w99.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.railway1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
		this.railway1.CanFocus = true;
		this.railway1.Name = "railway1";
		this.railway1.DrawIndicator = true;
		this.railway1.UseUnderline = true;
		this.railway1.Group = this.common1.Group;
		this.vbox3.Add(this.railway1);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.railway1]));
		w100.Position = 1;
		w100.Expand = false;
		w100.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.electrified1 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
		this.electrified1.CanFocus = true;
		this.electrified1.Name = "electrified1";
		this.electrified1.DrawIndicator = true;
		this.electrified1.UseUnderline = true;
		this.electrified1.Group = this.common1.Group;
		this.vbox3.Add(this.electrified1);
		global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.electrified1]));
		w101.Position = 2;
		w101.Expand = false;
		w101.Fill = false;
		this.table1.Add(this.vbox3);
		global::Gtk.Table.TableChild w102 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox3]));
		w102.TopAttach = ((uint)(1));
		w102.BottomAttach = ((uint)(2));
		w102.LeftAttach = ((uint)(1));
		w102.RightAttach = ((uint)(2));
		w102.XOptions = ((global::Gtk.AttachOptions)(4));
		w102.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.common2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
		this.common2.CanFocus = true;
		this.common2.Name = "common2";
		this.common2.DrawIndicator = true;
		this.common2.UseUnderline = true;
		this.common2.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.vbox4.Add(this.common2);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.common2]));
		w103.Position = 0;
		w103.Expand = false;
		w103.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.railway2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
		this.railway2.CanFocus = true;
		this.railway2.Name = "railway2";
		this.railway2.DrawIndicator = true;
		this.railway2.UseUnderline = true;
		this.railway2.Group = this.common2.Group;
		this.vbox4.Add(this.railway2);
		global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.railway2]));
		w104.Position = 1;
		w104.Expand = false;
		w104.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.electrified2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
		this.electrified2.CanFocus = true;
		this.electrified2.Name = "electrified2";
		this.electrified2.DrawIndicator = true;
		this.electrified2.UseUnderline = true;
		this.electrified2.Group = this.common2.Group;
		this.vbox4.Add(this.electrified2);
		global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.electrified2]));
		w105.Position = 2;
		w105.Expand = false;
		w105.Fill = false;
		this.table1.Add(this.vbox4);
		global::Gtk.Table.TableChild w106 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox4]));
		w106.TopAttach = ((uint)(3));
		w106.BottomAttach = ((uint)(4));
		w106.LeftAttach = ((uint)(1));
		w106.RightAttach = ((uint)(2));
		w106.XOptions = ((global::Gtk.AttachOptions)(4));
		w106.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.common3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
		this.common3.CanFocus = true;
		this.common3.Name = "common3";
		this.common3.DrawIndicator = true;
		this.common3.UseUnderline = true;
		this.common3.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.vbox5.Add(this.common3);
		global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.common3]));
		w107.Position = 0;
		w107.Expand = false;
		w107.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.railway3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
		this.railway3.CanFocus = true;
		this.railway3.Name = "railway3";
		this.railway3.DrawIndicator = true;
		this.railway3.UseUnderline = true;
		this.railway3.Group = this.common3.Group;
		this.vbox5.Add(this.railway3);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.railway3]));
		w108.Position = 1;
		w108.Expand = false;
		w108.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.electrified3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
		this.electrified3.CanFocus = true;
		this.electrified3.Name = "electrified3";
		this.electrified3.DrawIndicator = true;
		this.electrified3.UseUnderline = true;
		this.electrified3.Group = this.common3.Group;
		this.vbox5.Add(this.electrified3);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.electrified3]));
		w109.Position = 2;
		w109.Expand = false;
		w109.Fill = false;
		this.table1.Add(this.vbox5);
		global::Gtk.Table.TableChild w110 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox5]));
		w110.TopAttach = ((uint)(5));
		w110.BottomAttach = ((uint)(6));
		w110.LeftAttach = ((uint)(1));
		w110.RightAttach = ((uint)(2));
		w110.XOptions = ((global::Gtk.AttachOptions)(4));
		w110.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.common4 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
		this.common4.CanFocus = true;
		this.common4.Name = "common4";
		this.common4.DrawIndicator = true;
		this.common4.UseUnderline = true;
		this.common4.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.vbox6.Add(this.common4);
		global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.common4]));
		w111.Position = 0;
		w111.Expand = false;
		w111.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.railway4 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
		this.railway4.CanFocus = true;
		this.railway4.Name = "railway4";
		this.railway4.DrawIndicator = true;
		this.railway4.UseUnderline = true;
		this.railway4.Group = this.common4.Group;
		this.vbox6.Add(this.railway4);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.railway4]));
		w112.Position = 1;
		w112.Expand = false;
		w112.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.electrified4 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
		this.electrified4.CanFocus = true;
		this.electrified4.Name = "electrified4";
		this.electrified4.DrawIndicator = true;
		this.electrified4.UseUnderline = true;
		this.electrified4.Group = this.common4.Group;
		this.vbox6.Add(this.electrified4);
		global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.electrified4]));
		w113.Position = 2;
		w113.Expand = false;
		w113.Fill = false;
		this.table1.Add(this.vbox6);
		global::Gtk.Table.TableChild w114 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox6]));
		w114.TopAttach = ((uint)(7));
		w114.BottomAttach = ((uint)(8));
		w114.LeftAttach = ((uint)(1));
		w114.RightAttach = ((uint)(2));
		w114.XOptions = ((global::Gtk.AttachOptions)(4));
		w114.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.common5 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Common"));
		this.common5.CanFocus = true;
		this.common5.Name = "common5";
		this.common5.DrawIndicator = true;
		this.common5.UseUnderline = true;
		this.common5.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.vbox7.Add(this.common5);
		global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.common5]));
		w115.Position = 0;
		w115.Expand = false;
		w115.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.railway5 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Railway"));
		this.railway5.CanFocus = true;
		this.railway5.Name = "railway5";
		this.railway5.DrawIndicator = true;
		this.railway5.UseUnderline = true;
		this.railway5.Group = this.common5.Group;
		this.vbox7.Add(this.railway5);
		global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.railway5]));
		w116.Position = 1;
		w116.Expand = false;
		w116.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.electrified5 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Electrified"));
		this.electrified5.CanFocus = true;
		this.electrified5.Name = "electrified5";
		this.electrified5.DrawIndicator = true;
		this.electrified5.UseUnderline = true;
		this.electrified5.Group = this.common5.Group;
		this.vbox7.Add(this.electrified5);
		global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.electrified5]));
		w117.Position = 2;
		w117.Expand = false;
		w117.Fill = false;
		this.table1.Add(this.vbox7);
		global::Gtk.Table.TableChild w118 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox7]));
		w118.TopAttach = ((uint)(9));
		w118.BottomAttach = ((uint)(10));
		w118.LeftAttach = ((uint)(1));
		w118.RightAttach = ((uint)(2));
		w118.XOptions = ((global::Gtk.AttachOptions)(4));
		w118.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add(this.table1);
		global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table1]));
		w119.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table(((uint)(2)), ((uint)(4)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.elTime = new global::Gtk.Label();
		this.elTime.Name = "elTime";
		this.elTime.LabelProp = global::Mono.Unix.Catalog.GetString("Elapsed time:");
		this.table2.Add(this.elTime);
		global::Gtk.Table.TableChild w120 = ((global::Gtk.Table.TableChild)(this.table2[this.elTime]));
		w120.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.numTransport = new global::Gtk.Label();
		this.numTransport.Name = "numTransport";
		this.numTransport.LabelProp = global::Mono.Unix.Catalog.GetString("Number of transport:");
		this.table2.Add(this.numTransport);
		global::Gtk.Table.TableChild w121 = ((global::Gtk.Table.TableChild)(this.table2[this.numTransport]));
		w121.LeftAttach = ((uint)(3));
		w121.RightAttach = ((uint)(4));
		w121.XOptions = ((global::Gtk.AttachOptions)(4));
		w121.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.table2.Add(this.statusbar1);
		global::Gtk.Table.TableChild w122 = ((global::Gtk.Table.TableChild)(this.table2[this.statusbar1]));
		w122.TopAttach = ((uint)(1));
		w122.BottomAttach = ((uint)(2));
		w122.LeftAttach = ((uint)(3));
		w122.RightAttach = ((uint)(4));
		w122.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.statusbar2 = new global::Gtk.Statusbar();
		this.statusbar2.Name = "statusbar2";
		this.statusbar2.Spacing = 6;
		this.table2.Add(this.statusbar2);
		global::Gtk.Table.TableChild w123 = ((global::Gtk.Table.TableChild)(this.table2[this.statusbar2]));
		w123.TopAttach = ((uint)(1));
		w123.BottomAttach = ((uint)(2));
		w123.LeftAttach = ((uint)(2));
		w123.RightAttach = ((uint)(3));
		w123.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.statusbar3 = new global::Gtk.Statusbar();
		this.statusbar3.Name = "statusbar3";
		this.statusbar3.Spacing = 6;
		this.table2.Add(this.statusbar3);
		global::Gtk.Table.TableChild w124 = ((global::Gtk.Table.TableChild)(this.table2[this.statusbar3]));
		w124.TopAttach = ((uint)(1));
		w124.BottomAttach = ((uint)(2));
		w124.LeftAttach = ((uint)(1));
		w124.RightAttach = ((uint)(2));
		w124.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.statusbar4 = new global::Gtk.Statusbar();
		this.statusbar4.Name = "statusbar4";
		this.statusbar4.Spacing = 6;
		this.table2.Add(this.statusbar4);
		global::Gtk.Table.TableChild w125 = ((global::Gtk.Table.TableChild)(this.table2[this.statusbar4]));
		w125.TopAttach = ((uint)(1));
		w125.BottomAttach = ((uint)(2));
		w125.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.sumMoveTime = new global::Gtk.Label();
		this.sumMoveTime.Name = "sumMoveTime";
		this.sumMoveTime.LabelProp = global::Mono.Unix.Catalog.GetString("Total moveing time:");
		this.table2.Add(this.sumMoveTime);
		global::Gtk.Table.TableChild w126 = ((global::Gtk.Table.TableChild)(this.table2[this.sumMoveTime]));
		w126.LeftAttach = ((uint)(1));
		w126.RightAttach = ((uint)(2));
		w126.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.sumStopTime = new global::Gtk.Label();
		this.sumStopTime.Name = "sumStopTime";
		this.sumStopTime.LabelProp = global::Mono.Unix.Catalog.GetString("Total stop time:");
		this.table2.Add(this.sumStopTime);
		global::Gtk.Table.TableChild w127 = ((global::Gtk.Table.TableChild)(this.table2[this.sumStopTime]));
		w127.LeftAttach = ((uint)(2));
		w127.RightAttach = ((uint)(3));
		w127.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add(this.table2);
		global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table2]));
		w128.Position = 3;
		w128.Expand = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 960;
		this.DefaultHeight = 847;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.start_stop.Clicked += new global::System.EventHandler(this.ToggleProgress);
		this.button1.Clicked += new global::System.EventHandler(this.TransportInfo1_clicked);
	}
}
