
// This file has been generated by the GUI designer. Do not modify.
namespace Road111
{
	public partial class TransportDialog1
	{
		private global::Gtk.Table table5;

		private global::Gtk.Entry entry10;

		private global::Gtk.Entry entry7;

		private global::Gtk.Entry entry8;

		private global::Gtk.Entry entry9;

		private global::Gtk.Label Param1;

		private global::Gtk.Label Param2;

		private global::Gtk.Label Param3;

		private global::Gtk.Label Param4;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Road111.TransportDialog1
			this.Name = "Road111.TransportDialog1";
			this.WindowPosition = ((global::Gtk.WindowPosition)(2));
			this.Resizable = false;
			// Internal child Road111.TransportDialog1.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table5 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.entry10 = new global::Gtk.Entry();
			this.entry10.Sensitive = false;
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.Text = global::Mono.Unix.Catalog.GetString("param 4 value");
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '●';
			this.table5.Add(this.entry10);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table5[this.entry10]));
			w2.TopAttach = ((uint)(3));
			w2.BottomAttach = ((uint)(4));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry7 = new global::Gtk.Entry();
			this.entry7.Sensitive = false;
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.Text = global::Mono.Unix.Catalog.GetString("param 1 value");
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '●';
			this.table5.Add(this.entry7);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table5[this.entry7]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry8 = new global::Gtk.Entry();
			this.entry8.Sensitive = false;
			this.entry8.CanFocus = true;
			this.entry8.Name = "entry8";
			this.entry8.Text = global::Mono.Unix.Catalog.GetString("param 2 value");
			this.entry8.IsEditable = true;
			this.entry8.InvisibleChar = '●';
			this.table5.Add(this.entry8);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table5[this.entry8]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry9 = new global::Gtk.Entry();
			this.entry9.Sensitive = false;
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.Text = global::Mono.Unix.Catalog.GetString("param 3 value");
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '●';
			this.table5.Add(this.entry9);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table5[this.entry9]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.Param1 = new global::Gtk.Label();
			this.Param1.Name = "Param1";
			this.Param1.LabelProp = global::Mono.Unix.Catalog.GetString("Param1");
			this.table5.Add(this.Param1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table5[this.Param1]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.Param2 = new global::Gtk.Label();
			this.Param2.Name = "Param2";
			this.Param2.LabelProp = global::Mono.Unix.Catalog.GetString("Param2");
			this.table5.Add(this.Param2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table5[this.Param2]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.Param3 = new global::Gtk.Label();
			this.Param3.Name = "Param3";
			this.Param3.LabelProp = global::Mono.Unix.Catalog.GetString("Param3");
			this.table5.Add(this.Param3);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table5[this.Param3]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.Param4 = new global::Gtk.Label();
			this.Param4.Name = "Param4";
			this.Param4.LabelProp = global::Mono.Unix.Catalog.GetString("Param4");
			this.table5.Add(this.Param4);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table5[this.Param4]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.table5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1[this.table5]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Internal child Road111.TransportDialog1.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "dialog1_ActionArea";
			w11.Spacing = 10;
			w11.BorderWidth = ((uint)(5));
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11[this.buttonCancel]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11[this.buttonOk]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 524;
			this.DefaultHeight = 280;
			this.Show();
			this.buttonCancel.Clicked += new global::System.EventHandler(this.Cancel_Button);
			this.buttonOk.Clicked += new global::System.EventHandler(this.Ok_Button);
		}
	}
}
